"""initial_schema

Revision ID: bb0f836b8a6a
Revises: 
Create Date: 2025-11-29 16:35:26.998473+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'bb0f836b8a6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('orgs_slug_idx', 'orgs', ['slug'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('audit_logs_actor_idx', 'audit_logs', ['actor_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('audit_logs_org_created_idx', 'audit_logs', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('audit_logs_resource_idx', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('devices_org_active_idx', 'devices', ['org_id', 'is_active'], unique=False, postgresql_where='is_active = TRUE')
    op.create_index('devices_org_id_idx', 'devices', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='users_email_org_unique'),
    sa.UniqueConstraint('org_id', 'external_id', name='users_external_id_org_unique')
    )
    op.create_index('users_email_idx', 'users', ['email'], unique=False)
    op.create_index('users_external_id_idx', 'users', ['external_id'], unique=False)
    op.create_index('users_org_active_idx', 'users', ['org_id', 'is_active'], unique=False, postgresql_where='is_active = TRUE')
    op.create_index('users_org_id_idx', 'users', ['org_id'], unique=False)
    op.create_table('attendance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('attendance_logs_device_ts_idx', 'attendance_logs', ['device_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('attendance_logs_org_status_idx', 'attendance_logs', ['org_id', 'status'], unique=False)
    op.create_index('attendance_logs_org_user_ts_idx', 'attendance_logs', ['org_id', 'user_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('attendance_logs_ts_idx', 'attendance_logs', [sa.literal_column('ts DESC')], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(512), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('face_embeddings_user_id_idx', 'face_embeddings', ['user_id'], unique=False)
    op.create_index('face_embeddings_user_primary_idx', 'face_embeddings', ['user_id'], unique=True, postgresql_where='is_primary = TRUE')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('refresh_tokens_expires_idx', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('refresh_tokens_user_id_idx', 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('refresh_tokens_user_id_idx', table_name='refresh_tokens')
    op.drop_index('refresh_tokens_expires_idx', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('face_embeddings_user_primary_idx', table_name='face_embeddings', postgresql_where='is_primary = TRUE')
    op.drop_index('face_embeddings_user_id_idx', table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index('attendance_logs_ts_idx', table_name='attendance_logs')
    op.drop_index('attendance_logs_org_user_ts_idx', table_name='attendance_logs')
    op.drop_index('attendance_logs_org_status_idx', table_name='attendance_logs')
    op.drop_index('attendance_logs_device_ts_idx', table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index('users_org_id_idx', table_name='users')
    op.drop_index('users_org_active_idx', table_name='users', postgresql_where='is_active = TRUE')
    op.drop_index('users_external_id_idx', table_name='users')
    op.drop_index('users_email_idx', table_name='users')
    op.drop_table('users')
    op.drop_index('devices_org_id_idx', table_name='devices')
    op.drop_index('devices_org_active_idx', table_name='devices', postgresql_where='is_active = TRUE')
    op.drop_table('devices')
    op.drop_index('audit_logs_resource_idx', table_name='audit_logs')
    op.drop_index('audit_logs_org_created_idx', table_name='audit_logs')
    op.drop_index('audit_logs_actor_idx', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('orgs_slug_idx', table_name='orgs')
    op.drop_table('orgs')
    # ### end Alembic commands ###
